// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: alerts.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DnsAlerts_Dns_FullMethodName = "/alerts_proto.DnsAlerts/Dns"
)

// DnsAlertsClient is the client API for DnsAlerts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DnsAlertsClient interface {
	Dns(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DnsAlert, DnsAlert], error)
}

type dnsAlertsClient struct {
	cc grpc.ClientConnInterface
}

func NewDnsAlertsClient(cc grpc.ClientConnInterface) DnsAlertsClient {
	return &dnsAlertsClient{cc}
}

func (c *dnsAlertsClient) Dns(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DnsAlert, DnsAlert], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DnsAlerts_ServiceDesc.Streams[0], DnsAlerts_Dns_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DnsAlert, DnsAlert]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DnsAlerts_DnsClient = grpc.BidiStreamingClient[DnsAlert, DnsAlert]

// DnsAlertsServer is the server API for DnsAlerts service.
// All implementations must embed UnimplementedDnsAlertsServer
// for forward compatibility.
type DnsAlertsServer interface {
	Dns(grpc.BidiStreamingServer[DnsAlert, DnsAlert]) error
	mustEmbedUnimplementedDnsAlertsServer()
}

// UnimplementedDnsAlertsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDnsAlertsServer struct{}

func (UnimplementedDnsAlertsServer) Dns(grpc.BidiStreamingServer[DnsAlert, DnsAlert]) error {
	return status.Error(codes.Unimplemented, "method Dns not implemented")
}
func (UnimplementedDnsAlertsServer) mustEmbedUnimplementedDnsAlertsServer() {}
func (UnimplementedDnsAlertsServer) testEmbeddedByValue()                   {}

// UnsafeDnsAlertsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DnsAlertsServer will
// result in compilation errors.
type UnsafeDnsAlertsServer interface {
	mustEmbedUnimplementedDnsAlertsServer()
}

func RegisterDnsAlertsServer(s grpc.ServiceRegistrar, srv DnsAlertsServer) {
	// If the following call panics, it indicates UnimplementedDnsAlertsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DnsAlerts_ServiceDesc, srv)
}

func _DnsAlerts_Dns_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DnsAlertsServer).Dns(&grpc.GenericServerStream[DnsAlert, DnsAlert]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DnsAlerts_DnsServer = grpc.BidiStreamingServer[DnsAlert, DnsAlert]

// DnsAlerts_ServiceDesc is the grpc.ServiceDesc for DnsAlerts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DnsAlerts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerts_proto.DnsAlerts",
	HandlerType: (*DnsAlertsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dns",
			Handler:       _DnsAlerts_Dns_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "alerts.proto",
}

const (
	UiAlerts_Ui_FullMethodName = "/alerts_proto.UiAlerts/Ui"
)

// UiAlertsClient is the client API for UiAlerts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UiAlertsClient interface {
	Ui(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UiAlert, UiAlertReply], error)
}

type uiAlertsClient struct {
	cc grpc.ClientConnInterface
}

func NewUiAlertsClient(cc grpc.ClientConnInterface) UiAlertsClient {
	return &uiAlertsClient{cc}
}

func (c *uiAlertsClient) Ui(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UiAlert, UiAlertReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UiAlerts_ServiceDesc.Streams[0], UiAlerts_Ui_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UiAlert, UiAlertReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UiAlerts_UiClient = grpc.BidiStreamingClient[UiAlert, UiAlertReply]

// UiAlertsServer is the server API for UiAlerts service.
// All implementations must embed UnimplementedUiAlertsServer
// for forward compatibility.
type UiAlertsServer interface {
	Ui(grpc.BidiStreamingServer[UiAlert, UiAlertReply]) error
	mustEmbedUnimplementedUiAlertsServer()
}

// UnimplementedUiAlertsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUiAlertsServer struct{}

func (UnimplementedUiAlertsServer) Ui(grpc.BidiStreamingServer[UiAlert, UiAlertReply]) error {
	return status.Error(codes.Unimplemented, "method Ui not implemented")
}
func (UnimplementedUiAlertsServer) mustEmbedUnimplementedUiAlertsServer() {}
func (UnimplementedUiAlertsServer) testEmbeddedByValue()                  {}

// UnsafeUiAlertsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UiAlertsServer will
// result in compilation errors.
type UnsafeUiAlertsServer interface {
	mustEmbedUnimplementedUiAlertsServer()
}

func RegisterUiAlertsServer(s grpc.ServiceRegistrar, srv UiAlertsServer) {
	// If the following call panics, it indicates UnimplementedUiAlertsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UiAlerts_ServiceDesc, srv)
}

func _UiAlerts_Ui_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UiAlertsServer).Ui(&grpc.GenericServerStream[UiAlert, UiAlertReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UiAlerts_UiServer = grpc.BidiStreamingServer[UiAlert, UiAlertReply]

// UiAlerts_ServiceDesc is the grpc.ServiceDesc for UiAlerts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UiAlerts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerts_proto.UiAlerts",
	HandlerType: (*UiAlertsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ui",
			Handler:       _UiAlerts_Ui_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "alerts.proto",
}
