// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: alerts.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DnsAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsAlert) Reset() {
	*x = DnsAlert{}
	mi := &file_alerts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsAlert) ProtoMessage() {}

func (x *DnsAlert) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsAlert.ProtoReflect.Descriptor instead.
func (*DnsAlert) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *DnsAlert) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DnsAlert) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DnsAlert) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type DnsAlertReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsAlertReply) Reset() {
	*x = DnsAlertReply{}
	mi := &file_alerts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsAlertReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsAlertReply) ProtoMessage() {}

func (x *DnsAlertReply) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsAlertReply.ProtoReflect.Descriptor instead.
func (*DnsAlertReply) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *DnsAlertReply) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type UiAlert struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ThreatCategory    string                 `protobuf:"bytes,1,opt,name=threatCategory,proto3" json:"threatCategory,omitempty"`
	ThreatSubCategory string                 `protobuf:"bytes,2,opt,name=threatSubCategory,proto3" json:"threatSubCategory,omitempty"`
	ThreatEntityName  string                 `protobuf:"bytes,3,opt,name=threatEntityName,proto3" json:"threatEntityName,omitempty"`
	ThreatIntelSource string                 `protobuf:"bytes,4,opt,name=threatIntelSource,proto3" json:"threatIntelSource,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UiAlert) Reset() {
	*x = UiAlert{}
	mi := &file_alerts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UiAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UiAlert) ProtoMessage() {}

func (x *UiAlert) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UiAlert.ProtoReflect.Descriptor instead.
func (*UiAlert) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{2}
}

func (x *UiAlert) GetThreatCategory() string {
	if x != nil {
		return x.ThreatCategory
	}
	return ""
}

func (x *UiAlert) GetThreatSubCategory() string {
	if x != nil {
		return x.ThreatSubCategory
	}
	return ""
}

func (x *UiAlert) GetThreatEntityName() string {
	if x != nil {
		return x.ThreatEntityName
	}
	return ""
}

func (x *UiAlert) GetThreatIntelSource() string {
	if x != nil {
		return x.ThreatIntelSource
	}
	return ""
}

type UiAlertReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAction    string                 `protobuf:"bytes,1,opt,name=userAction,proto3" json:"userAction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UiAlertReply) Reset() {
	*x = UiAlertReply{}
	mi := &file_alerts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UiAlertReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UiAlertReply) ProtoMessage() {}

func (x *UiAlertReply) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UiAlertReply.ProtoReflect.Descriptor instead.
func (*UiAlertReply) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{3}
}

func (x *UiAlertReply) GetUserAction() string {
	if x != nil {
		return x.UserAction
	}
	return ""
}

var File_alerts_proto protoreflect.FileDescriptor

const file_alerts_proto_rawDesc = "" +
	"\n" +
	"\falerts.proto\x12\falerts_proto\"Z\n" +
	"\bDnsAlert\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"!\n" +
	"\rDnsAlertReply\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\"\xb9\x01\n" +
	"\aUiAlert\x12&\n" +
	"\x0ethreatCategory\x18\x01 \x01(\tR\x0ethreatCategory\x12,\n" +
	"\x11threatSubCategory\x18\x02 \x01(\tR\x11threatSubCategory\x12*\n" +
	"\x10threatEntityName\x18\x03 \x01(\tR\x10threatEntityName\x12,\n" +
	"\x11threatIntelSource\x18\x04 \x01(\tR\x11threatIntelSource\".\n" +
	"\fUiAlertReply\x12\x1e\n" +
	"\n" +
	"userAction\x18\x01 \x01(\tR\n" +
	"userAction2Q\n" +
	"\x0fDnsAlertService\x12>\n" +
	"\x03Dns\x12\x16.alerts_proto.DnsAlert\x1a\x1b.alerts_proto.DnsAlertReply(\x010\x012M\n" +
	"\x0eUiAlertService\x12;\n" +
	"\x02Ui\x12\x15.alerts_proto.UiAlert\x1a\x1a.alerts_proto.UiAlertReply(\x010\x01B\x03Z\x01.b\x06proto3"

var (
	file_alerts_proto_rawDescOnce sync.Once
	file_alerts_proto_rawDescData []byte
)

func file_alerts_proto_rawDescGZIP() []byte {
	file_alerts_proto_rawDescOnce.Do(func() {
		file_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)))
	})
	return file_alerts_proto_rawDescData
}

var file_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_alerts_proto_goTypes = []any{
	(*DnsAlert)(nil),      // 0: alerts_proto.DnsAlert
	(*DnsAlertReply)(nil), // 1: alerts_proto.DnsAlertReply
	(*UiAlert)(nil),       // 2: alerts_proto.UiAlert
	(*UiAlertReply)(nil),  // 3: alerts_proto.UiAlertReply
}
var file_alerts_proto_depIdxs = []int32{
	0, // 0: alerts_proto.DnsAlertService.Dns:input_type -> alerts_proto.DnsAlert
	2, // 1: alerts_proto.UiAlertService.Ui:input_type -> alerts_proto.UiAlert
	1, // 2: alerts_proto.DnsAlertService.Dns:output_type -> alerts_proto.DnsAlertReply
	3, // 3: alerts_proto.UiAlertService.Ui:output_type -> alerts_proto.UiAlertReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alerts_proto_init() }
func file_alerts_proto_init() {
	if File_alerts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_alerts_proto_goTypes,
		DependencyIndexes: file_alerts_proto_depIdxs,
		MessageInfos:      file_alerts_proto_msgTypes,
	}.Build()
	File_alerts_proto = out.File
	file_alerts_proto_goTypes = nil
	file_alerts_proto_depIdxs = nil
}
