// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: alerts.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DnsAlerts_DnsAlerts_FullMethodName = "/alerts_proto.DnsAlerts/DnsAlerts"
)

// DnsAlertsClient is the client API for DnsAlerts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DnsAlertsClient interface {
	DnsAlerts(ctx context.Context, in *DnsThreat, opts ...grpc.CallOption) (*DnsReply, error)
}

type dnsAlertsClient struct {
	cc grpc.ClientConnInterface
}

func NewDnsAlertsClient(cc grpc.ClientConnInterface) DnsAlertsClient {
	return &dnsAlertsClient{cc}
}

func (c *dnsAlertsClient) DnsAlerts(ctx context.Context, in *DnsThreat, opts ...grpc.CallOption) (*DnsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DnsReply)
	err := c.cc.Invoke(ctx, DnsAlerts_DnsAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DnsAlertsServer is the server API for DnsAlerts service.
// All implementations must embed UnimplementedDnsAlertsServer
// for forward compatibility.
type DnsAlertsServer interface {
	DnsAlerts(context.Context, *DnsThreat) (*DnsReply, error)
	mustEmbedUnimplementedDnsAlertsServer()
}

// UnimplementedDnsAlertsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDnsAlertsServer struct{}

func (UnimplementedDnsAlertsServer) DnsAlerts(context.Context, *DnsThreat) (*DnsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DnsAlerts not implemented")
}
func (UnimplementedDnsAlertsServer) mustEmbedUnimplementedDnsAlertsServer() {}
func (UnimplementedDnsAlertsServer) testEmbeddedByValue()                   {}

// UnsafeDnsAlertsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DnsAlertsServer will
// result in compilation errors.
type UnsafeDnsAlertsServer interface {
	mustEmbedUnimplementedDnsAlertsServer()
}

func RegisterDnsAlertsServer(s grpc.ServiceRegistrar, srv DnsAlertsServer) {
	// If the following call panics, it indicates UnimplementedDnsAlertsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DnsAlerts_ServiceDesc, srv)
}

func _DnsAlerts_DnsAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DnsThreat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DnsAlertsServer).DnsAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DnsAlerts_DnsAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DnsAlertsServer).DnsAlerts(ctx, req.(*DnsThreat))
	}
	return interceptor(ctx, in, info, handler)
}

// DnsAlerts_ServiceDesc is the grpc.ServiceDesc for DnsAlerts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DnsAlerts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerts_proto.DnsAlerts",
	HandlerType: (*DnsAlertsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DnsAlerts",
			Handler:    _DnsAlerts_DnsAlerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alerts.proto",
}
