// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: alerts.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DnsThreat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsThreat) Reset() {
	*x = DnsThreat{}
	mi := &file_alerts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsThreat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsThreat) ProtoMessage() {}

func (x *DnsThreat) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsThreat.ProtoReflect.Descriptor instead.
func (*DnsThreat) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *DnsThreat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DnsThreat) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DnsThreat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DnsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsReply) Reset() {
	*x = DnsReply{}
	mi := &file_alerts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsReply) ProtoMessage() {}

func (x *DnsReply) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsReply.ProtoReflect.Descriptor instead.
func (*DnsReply) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *DnsReply) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

var File_alerts_proto protoreflect.FileDescriptor

const file_alerts_proto_rawDesc = "" +
	"\n" +
	"\falerts.proto\x12\falerts_proto\"S\n" +
	"\tDnsThreat\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\x1c\n" +
	"\bDnsReply\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack2M\n" +
	"\tDnsAlerts\x12@\n" +
	"\rDnsAlertFound\x12\x17.alerts_proto.DnsThreat\x1a\x16.alerts_proto.DnsReplyB\x03Z\x01.b\x06proto3"

var (
	file_alerts_proto_rawDescOnce sync.Once
	file_alerts_proto_rawDescData []byte
)

func file_alerts_proto_rawDescGZIP() []byte {
	file_alerts_proto_rawDescOnce.Do(func() {
		file_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)))
	})
	return file_alerts_proto_rawDescData
}

var file_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alerts_proto_goTypes = []any{
	(*DnsThreat)(nil), // 0: alerts_proto.DnsThreat
	(*DnsReply)(nil),  // 1: alerts_proto.DnsReply
}
var file_alerts_proto_depIdxs = []int32{
	0, // 0: alerts_proto.DnsAlerts.DnsAlertFound:input_type -> alerts_proto.DnsThreat
	1, // 1: alerts_proto.DnsAlerts.DnsAlertFound:output_type -> alerts_proto.DnsReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alerts_proto_init() }
func file_alerts_proto_init() {
	if File_alerts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alerts_proto_goTypes,
		DependencyIndexes: file_alerts_proto_depIdxs,
		MessageInfos:      file_alerts_proto_msgTypes,
	}.Build()
	File_alerts_proto = out.File
	file_alerts_proto_goTypes = nil
	file_alerts_proto_depIdxs = nil
}
