// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: alerts.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DnsAlertService_Dns_FullMethodName = "/alerts_proto.DnsAlertService/Dns"
)

// DnsAlertServiceClient is the client API for DnsAlertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DnsAlertServiceClient interface {
	Dns(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DnsAlert, DnsAlertReply], error)
}

type dnsAlertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDnsAlertServiceClient(cc grpc.ClientConnInterface) DnsAlertServiceClient {
	return &dnsAlertServiceClient{cc}
}

func (c *dnsAlertServiceClient) Dns(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DnsAlert, DnsAlertReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DnsAlertService_ServiceDesc.Streams[0], DnsAlertService_Dns_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DnsAlert, DnsAlertReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DnsAlertService_DnsClient = grpc.BidiStreamingClient[DnsAlert, DnsAlertReply]

// DnsAlertServiceServer is the server API for DnsAlertService service.
// All implementations must embed UnimplementedDnsAlertServiceServer
// for forward compatibility.
type DnsAlertServiceServer interface {
	Dns(grpc.BidiStreamingServer[DnsAlert, DnsAlertReply]) error
	mustEmbedUnimplementedDnsAlertServiceServer()
}

// UnimplementedDnsAlertServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDnsAlertServiceServer struct{}

func (UnimplementedDnsAlertServiceServer) Dns(grpc.BidiStreamingServer[DnsAlert, DnsAlertReply]) error {
	return status.Error(codes.Unimplemented, "method Dns not implemented")
}
func (UnimplementedDnsAlertServiceServer) mustEmbedUnimplementedDnsAlertServiceServer() {}
func (UnimplementedDnsAlertServiceServer) testEmbeddedByValue()                         {}

// UnsafeDnsAlertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DnsAlertServiceServer will
// result in compilation errors.
type UnsafeDnsAlertServiceServer interface {
	mustEmbedUnimplementedDnsAlertServiceServer()
}

func RegisterDnsAlertServiceServer(s grpc.ServiceRegistrar, srv DnsAlertServiceServer) {
	// If the following call panics, it indicates UnimplementedDnsAlertServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DnsAlertService_ServiceDesc, srv)
}

func _DnsAlertService_Dns_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DnsAlertServiceServer).Dns(&grpc.GenericServerStream[DnsAlert, DnsAlertReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DnsAlertService_DnsServer = grpc.BidiStreamingServer[DnsAlert, DnsAlertReply]

// DnsAlertService_ServiceDesc is the grpc.ServiceDesc for DnsAlertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DnsAlertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerts_proto.DnsAlertService",
	HandlerType: (*DnsAlertServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dns",
			Handler:       _DnsAlertService_Dns_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "alerts.proto",
}

const (
	UiAlertService_Ui_FullMethodName = "/alerts_proto.UiAlertService/Ui"
)

// UiAlertServiceClient is the client API for UiAlertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UiAlertServiceClient interface {
	Ui(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UiAlert, UiAlertReply], error)
}

type uiAlertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUiAlertServiceClient(cc grpc.ClientConnInterface) UiAlertServiceClient {
	return &uiAlertServiceClient{cc}
}

func (c *uiAlertServiceClient) Ui(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UiAlert, UiAlertReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UiAlertService_ServiceDesc.Streams[0], UiAlertService_Ui_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UiAlert, UiAlertReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UiAlertService_UiClient = grpc.BidiStreamingClient[UiAlert, UiAlertReply]

// UiAlertServiceServer is the server API for UiAlertService service.
// All implementations must embed UnimplementedUiAlertServiceServer
// for forward compatibility.
type UiAlertServiceServer interface {
	Ui(grpc.BidiStreamingServer[UiAlert, UiAlertReply]) error
	mustEmbedUnimplementedUiAlertServiceServer()
}

// UnimplementedUiAlertServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUiAlertServiceServer struct{}

func (UnimplementedUiAlertServiceServer) Ui(grpc.BidiStreamingServer[UiAlert, UiAlertReply]) error {
	return status.Error(codes.Unimplemented, "method Ui not implemented")
}
func (UnimplementedUiAlertServiceServer) mustEmbedUnimplementedUiAlertServiceServer() {}
func (UnimplementedUiAlertServiceServer) testEmbeddedByValue()                        {}

// UnsafeUiAlertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UiAlertServiceServer will
// result in compilation errors.
type UnsafeUiAlertServiceServer interface {
	mustEmbedUnimplementedUiAlertServiceServer()
}

func RegisterUiAlertServiceServer(s grpc.ServiceRegistrar, srv UiAlertServiceServer) {
	// If the following call panics, it indicates UnimplementedUiAlertServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UiAlertService_ServiceDesc, srv)
}

func _UiAlertService_Ui_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UiAlertServiceServer).Ui(&grpc.GenericServerStream[UiAlert, UiAlertReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UiAlertService_UiServer = grpc.BidiStreamingServer[UiAlert, UiAlertReply]

// UiAlertService_ServiceDesc is the grpc.ServiceDesc for UiAlertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UiAlertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerts_proto.UiAlertService",
	HandlerType: (*UiAlertServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ui",
			Handler:       _UiAlertService_Ui_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "alerts.proto",
}
