// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: ca.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewCert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          string                 `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewCert) Reset() {
	*x = NewCert{}
	mi := &file_ca_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCert) ProtoMessage() {}

func (x *NewCert) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCert.ProtoReflect.Descriptor instead.
func (*NewCert) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{0}
}

func (x *NewCert) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

var File_ca_proto protoreflect.FileDescriptor

const file_ca_proto_rawDesc = "" +
	"\n" +
	"\bca.proto\x12\falerts_proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n" +
	"\aNewCert\x12\x12\n" +
	"\x04cert\x18\x01 \x01(\tR\x04cert2A\n" +
	"\bUpdateCA\x125\n" +
	"\x02CA\x12\x15.alerts_proto.NewCert\x1a\x16.google.protobuf.Empty(\x01B\x03Z\x01.b\x06proto3"

var (
	file_ca_proto_rawDescOnce sync.Once
	file_ca_proto_rawDescData []byte
)

func file_ca_proto_rawDescGZIP() []byte {
	file_ca_proto_rawDescOnce.Do(func() {
		file_ca_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ca_proto_rawDesc), len(file_ca_proto_rawDesc)))
	})
	return file_ca_proto_rawDescData
}

var file_ca_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ca_proto_goTypes = []any{
	(*NewCert)(nil),       // 0: alerts_proto.NewCert
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_ca_proto_depIdxs = []int32{
	0, // 0: alerts_proto.UpdateCA.CA:input_type -> alerts_proto.NewCert
	1, // 1: alerts_proto.UpdateCA.CA:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ca_proto_init() }
func file_ca_proto_init() {
	if File_ca_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ca_proto_rawDesc), len(file_ca_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ca_proto_goTypes,
		DependencyIndexes: file_ca_proto_depIdxs,
		MessageInfos:      file_ca_proto_msgTypes,
	}.Build()
	File_ca_proto = out.File
	file_ca_proto_goTypes = nil
	file_ca_proto_depIdxs = nil
}
