// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: ca.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpdateCA_CA_FullMethodName = "/alerts_proto.UpdateCA/CA"
)

// UpdateCAClient is the client API for UpdateCA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateCAClient interface {
	CA(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NewCert, emptypb.Empty], error)
}

type updateCAClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateCAClient(cc grpc.ClientConnInterface) UpdateCAClient {
	return &updateCAClient{cc}
}

func (c *updateCAClient) CA(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NewCert, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UpdateCA_ServiceDesc.Streams[0], UpdateCA_CA_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NewCert, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpdateCA_CAClient = grpc.ClientStreamingClient[NewCert, emptypb.Empty]

// UpdateCAServer is the server API for UpdateCA service.
// All implementations must embed UnimplementedUpdateCAServer
// for forward compatibility.
type UpdateCAServer interface {
	CA(grpc.ClientStreamingServer[NewCert, emptypb.Empty]) error
	mustEmbedUnimplementedUpdateCAServer()
}

// UnimplementedUpdateCAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateCAServer struct{}

func (UnimplementedUpdateCAServer) CA(grpc.ClientStreamingServer[NewCert, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method CA not implemented")
}
func (UnimplementedUpdateCAServer) mustEmbedUnimplementedUpdateCAServer() {}
func (UnimplementedUpdateCAServer) testEmbeddedByValue()                  {}

// UnsafeUpdateCAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateCAServer will
// result in compilation errors.
type UnsafeUpdateCAServer interface {
	mustEmbedUnimplementedUpdateCAServer()
}

func RegisterUpdateCAServer(s grpc.ServiceRegistrar, srv UpdateCAServer) {
	// If the following call panics, it indicates UnimplementedUpdateCAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdateCA_ServiceDesc, srv)
}

func _UpdateCA_CA_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UpdateCAServer).CA(&grpc.GenericServerStream[NewCert, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpdateCA_CAServer = grpc.ClientStreamingServer[NewCert, emptypb.Empty]

// UpdateCA_ServiceDesc is the grpc.ServiceDesc for UpdateCA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateCA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerts_proto.UpdateCA",
	HandlerType: (*UpdateCAServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CA",
			Handler:       _UpdateCA_CA_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ca.proto",
}
